---
name: build-presentation-exchange-swift
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          fastlane tests # fastlane just_build
