---
name: build-presentation-exchange-swift
on:
  push:
    branches: ['main']
    tags: [ v* ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          fastlane tests # fastlane just_build
